### ISSUE TITLE
Pip-installable

### ISSUE THREAD

**Issue by alvinwan** [python-constraint/python-constraint#14]
Is or will this lib be pip-installable? Looks nifty. For now, I've copied/pasted `constraints/` and linked to your repo. Thanks for porting this.

https://github.com/alvinwan/piipod/blob/master/constraint/__init__.py#L3

**Comment by scls19fr** [comment]
@niemeyer didn't upload to PyPi... so for now it's not pip installable but I suggest not to copy/paste like you did but to install using

    pip install git+https://github.com/python-constraint/python-constraint.git

**Comment by alvinwan** [comment]
Oh cool, thanks!
