### ISSUE TITLE
python3 generator .next() not available

### ISSUE THREAD

**Issue by tomsajan** [python-constraint/python-constraint#15]
Please update the file `__init__.py` on line 543. Python 3 does not support .next() on iterator.
Instead use:
`return next(iter)`

**Comment by scls19fr** [comment]
Could you provide a minimal example to show that it doesn't work under Python 3 (and work under Python 2)
so that it will be possible to add a unit test and fix this issue.

**Comment by scls19fr** [comment]
See also https://github.com/python-constraint/python-constraint/issues/12

**Comment by tomsajan** [comment]
Thank you for the quick fix. The next() built-in function is available both in python 2 and 3 (according to doc). So this fix should work for both versions. It calls the iterator's .next() (in python2) or .__next__() (python3) function.

The minimal example could be:
from constraint import *
problem = Problem()
problem.addVariables(['a', 'b'], range(4))
problem.addConstraint(AllDifferentConstraint(), ['a', 'b'])
problem.getSolution()

This did not work in the previous version for python 3, but worked in python 2.

**Comment by scls19fr** [comment]
You might use one backquote for inline code and 3 backquote for long code.
