### ISSUE TITLE
Python 3 Incompatibility (?)

### ISSUE THREAD

**Issue by evancox10** [python-constraint/python-constraint#34]
On lines 691-692 of `__init__.py` in the `minConflicts.getSolution(...)` method, you have the following:

```
lst = domains.keys()
random.shuffle(lst)

The call to random.shuffle() fails on python 3, because in python3 the dictionary .keys() method returns a set, which can't be indexed. So lst must be converted from this set into a list:

lst = list(domains.keys())
random.shuffle(lst)
```

Not sure how you would write the code to be compatible in both Python2 and Python3

**Comment by agriffis** [comment]
In Python 3 `domains.keys()` returns an iterator, not a set.

Wrapping in `list()` is a reasonable approach that's compatible on both Python 2 and 3.

Want to provide a PR?

**Comment by evancox10** [comment]
I'll provide a PR this weekend, thanks!

**Comment by scls19fr** [comment]
@evancox10 Could you ideally send a PR with a test showing it's currently broken with Python 3 and a fix to make this test pass?

**Comment by agriffis** [comment]
@evancox10 Just to clarify what @scls19fr said, it doesn't need to specifically be a test for your fix. Adding tests for `MinConflictsSolver` should do the trick since it's not covered yet, and Travis will show the build failing or succeeding in your PR. https://coveralls.io/builds/13020985/source?filename=constraint%2F__init__.py#L647

**Comment by deceze** [comment]
Same issue in `Constraint.preProcess`, trying to access `variables[0]`, coming from `domain.keys()` in `Problem._getArgs`.

**Comment by codito** [comment]
Seeing the same issue @deceze. Anyone actively working on a fix?

**Comment by codito** [comment]
Created a PR for `Constraint.preProcess` issue: https://github.com/python-constraint/python-constraint/pull/37. Please review.
