### ISSUE TITLE
Use bipartite graph matching algorithm for alldifferent global constraint

### ISSUE THREAD

**Issue by LemonPi** [python-constraint/python-constraint#40]
Are there any plans to improve the performance of the alldifferent global constraint?
The current approach checks feasibility well, but doesn't contribute to pruning.
You can get a lot of pruning done using this constraint by using an algorithm that involves finding the maximum matching of a bipartite graph (graph where variables and values are the bipartite vertices and edges are between the variables and values in their domains).

Check it out https://www.andrew.cmu.edu/user/vanhoeve/papers/alldiff.pdf

**Comment by scls19fr** [comment]
There is currently no plan to improve the performance of the alldifferent global constraint.
Althought I'm open to PR with unit tests.

**Comment by LemonPi** [comment]
I'm building my own CP solver for practice. It has some features missing from python-constraint (arc consistency propagation - why is this disabled?). If I get far enough and those features work I'll see if I can make a pull request.
