### ISSUE TITLE
Constraints do not work properly if added in a for-loop

### ISSUE THREAD

**Issue by njlxyaoxinwei** [python-constraint/python-constraint#48]
I am using the latest github version of python-constraint with Python 3.7.0 on Ubuntu 18.04.1

Minimum Reproduction:
```
import constraint
p  = constraint.Problem()
p.addVariable('x', [0])

for val in [False, True]:
    p.addConstraint(lambda x: val, ['x'])
print(p.getSolution())

p  = constraint.Problem()
p.addVariable('x', [0])

p.addConstraint(lambda x: False, ['x'])
p.addConstraint(lambda x: True, ['x'])
print(p.getSolution())

```

The code snippet above gives the following output:
```
{'x':0}
None
```

**Comment by njlxyaoxinwei** [comment]
It turns out to be an issue with the code wrt variable capture in python lambdas.  Closing now.

**Comment by scls19fr** [comment]
No problem @njlxyaoxinwei. Feel free to contribute here!

**Comment by eyaler** [comment]
i was hitting this issue too due to this gotcha: https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture. may be this should be mentioned in the docs?

**Comment by BenjaminPoilve** [comment]
Same here, if you are a bit rusty about lamba capture scope, this is not trivial. I had to go back to the rook example to notice that the loop iterator were explicitly captured.
