### ISSUE TITLE
addVariable doesn't properly support Domain subclasses

### ISSUE THREAD

**Issue by WillDHB** [python-constraint/python-constraint#50]
It seems like addVariable is intended to support using a subclass of Domain as a domain.  However, this logic:

`if hasattr(domain, "__getitem__"):
    domain = Domain(domain)
elif isinstance(domain, Domain):
    domain = copy.copy(domain)
`
will always convert to a Domain, since Domain objects implement __getitem__.  It would appear that replacing it with this code would fix it:

`if isinstance(domain, Domain):
    domain = copy.copy(domain)
elif hasattr(domain, "__getitem__"):
    domain = Domain(domain)
`

**Comment by scls19fr** [comment]
Hi @WillDHB 

PR with tests are always welcome

Kind regards

**Comment by WillDHB** [comment]
Done.  Sorry the code in the bug report was mangled; I didn't notice until just now.

**Comment by scls19fr** [comment]
To avoid code to be mangled, you just need triple backtick (see my edit)
