### ISSUE TITLE
Arrays with constraints

### ISSUE THREAD

**Issue by aryanlall11** [python-constraint/python-constraint#58]
Suppose you have a variable "num" and an array "arr". Both are added to the Problem().
How can you add a constraint like **arr.size()==num**? (The array size should be equal to the num variable)
Thanks in advance

**Comment by sk-surya** [comment]
@aryanlall11 I'm curious to see what you were trying to solve.

**Comment by aryanlall11** [comment]
> @aryanlall11 I'm curious to see what you were trying to solve.

I was trying to solve a constraint randomization problem, where a set of random values need to be generated which satisfies some constraints. There could be multiple constraints imposed on the values, and in one case I was required to deal with the above problem.
However, I implemented the model just to know that it's extremely slow XD. Thus I created my own iterative constraint randomization solver and optimized it for my particular task. Currently, I am not using this library.
