### ISSUE TITLE
Problems with the basic example

### ISSUE THREAD

**Issue by jolammi** [python-constraint/python-constraint#74]
I'm trying to run the basic example and I just can't get it to work:

```python
from constraint import *

problem = Problem()
problem.addVariable("a", [1, 2, 3])
problem.addVariable("b", [4, 5, 6])
print(problem.getSolutions())

problem.addConstraint(lambda a, b: a * 2 == ("a", "b"))
print(problem.getSolutions())
```

Output:
```
[{'a': 3, 'b': 6}, {'a': 3, 'b': 5}, {'a': 3, 'b': 4}, {'a': 2, 'b': 6}, {'a': 2, 'b': 5}, {'a': 2, 'b': 4}, {'a': 1, 'b': 6}, {'a': 1, 'b': 5}, {'a': 1, 'b': 4}]
[]
```

I tried with Python 3.10, 3.6, 3.5 and 2.7, with the newest version, and versions 1.3.1 and 1.3 in Python 3.6. Every time I get an empty list for the solutions. What could be the problem?

OS: Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by Erik-Hoffmann** [comment]
You have a typo at `problem.addConstraint(lambda a, b: a * 2 == ("a", "b"))`

It should be `problem.addConstraint(lambda a, b: a * 2 == b,  ("a", "b"))`

**Comment by jolammi** [comment]
Oh dear, what a fool I've been. Thanks for your help!
