### ISSUE TITLE
Include test code in source distribution to enable testing on conda-forge?

### ISSUE THREAD

**Issue by bouweandela** [python-constraint/python-constraint#80]
It would be useful to include the test code in the source distribution, as this would allow us to test the built package on conda-forge. Would this be possible?

**Comment by bouweandela** [comment]
Related to https://github.com/conda-forge/staged-recipes/pull/24420

**Comment by fjwillemsen** [comment]
Tests source has been added to the source distribution. This is available as of 2.0.0b4. Closing for now, feel free to reopen if necessary.

**Comment by bouweandela** [comment]
Thanks!
